# Generated by Django 3.1.7 on 2021-05-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('S', 'Serviço'), ('P', 'Produto')], default='S', max_length=1)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicocliente',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='servicocliente',
            name='tipo',
        ),
        migrations.AddField(
            model_name='servicocliente',
            name='servico_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beauty.servicoproduto'),
        ),
    ]
